services:
  - type: web
    name: sign
    env: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: PUBLIC_BASE_URL
        sync: false
      - key: TEMP_CASE_TTL_HOURS
        value: 4
      - key: MAX_UPLOAD_SIZE_MB
        value: 5
